version: "3.8"

services:
  client:
    build: ./backOffice
    ports:
      - 3000:3000
    volumes:
      - ./backOffice/src:/app/src
  server:
    build: ./serverNode
    ports:
      - 5000:5000
    volumes:
      - ./serverNode/src:/app/src